name: pgkylSrcH5
channels:
  - defaults
  - conda-forge
dependencies:
  - click>=8.1.7
  - matplotlib>=3.7.0
  - msgpack-python>=1.0.3
  - numpy>=1.24.4,<2
  - pytables>=3.8.0
  - pytest>=7.4.0
  - python>=3.11
  - scipy>=1.10.1
  - sympy>=1.12
  - h5py
